version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - mongodb:mongodb
    volumes:
      - web-data:/usr/src/app/static
    environment:
      MONGODB_DATABASE: admin
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: 123456
      MONGODB_HOSTNAME: mongodb
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: always
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  nginx:
    image: nginx:latest
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - web:web

volumes:
    web-data:
    mongodbdata:
